-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 10:57:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbDotCLASS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbDotCLASS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbDotCLASS` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `mydbDotCLASS` ;

-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idciudad`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`usuario` (
  `idusuario` INT NOT NULL,
  `nickname` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `id_pais` INT NOT NULL,
  `id_ciudad` INT NOT NULL,
  `descripcion` TEXT NULL,
  `numero_seguidores` INT NOT NULL,
  `pregunta_seguridad` TEXT NOT NULL,
  `respuesta_seguridad` TEXT NOT NULL,
  `foto` VARCHAR(100) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  INDEX `idpais_idx` (`id_pais` ASC) VISIBLE,
  INDEX `fk_usuario_ciudad1_idx` (`id_ciudad` ASC) VISIBLE,
  CONSTRAINT `idpais`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydbDotCLASS`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ciudad1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `mydbDotCLASS`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_curso_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydbDotCLASS`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`docente` (
  `iddocente` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`iddocente`),
  INDEX `fk_docente_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_docente_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_docente_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydbDotCLASS`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydbDotCLASS`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`bonificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`bonificacion` (
  `idbonificacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_docente` INT NOT NULL,
  `monto` DECIMAL NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idbonificacion`),
  INDEX `fk_bonificacion_docente1_idx` (`id_docente` ASC) VISIBLE,
  INDEX `fk_bonificacion_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_bonificacion_docente1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `mydbDotCLASS`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bonificacion_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydbDotCLASS`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`suscripcion` (
  `idsuscripcion` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_bonificacion` INT NOT NULL,
  PRIMARY KEY (`idsuscripcion`),
  INDEX `fk_suscripcion_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_suscripcion_bonificacion1_idx` (`id_bonificacion` ASC) VISIBLE,
  CONSTRAINT `fk_suscripcion_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydbDotCLASS`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suscripcion_bonificacion1`
    FOREIGN KEY (`id_bonificacion`)
    REFERENCES `mydbDotCLASS`.`bonificacion` (`idbonificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`seccion` (
  `idseccion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`idseccion`),
  INDEX `fk_seccion_curso1_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_seccion_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydbDotCLASS`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`marcador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`marcador` (
  `idmarcador` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idmarcador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`aporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`aporte` (
  `idaporte` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idaporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idcomentario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`asistencia` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idasistencia`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`clase` (
  `idclase` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_seccion` INT NOT NULL,
  PRIMARY KEY (`idclase`),
  INDEX `fk_clase_seccion1_idx` (`id_seccion` ASC) VISIBLE,
  CONSTRAINT `fk_clase_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `mydbDotCLASS`.`seccion` (`idseccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`movimientos_clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`movimientos_clase` (
  `id_movimientos_clase` INT NOT NULL AUTO_INCREMENT,
  `id_clase` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `id_asistencia` INT NULL,
  `id_comentario` INT NULL,
  `id_marcador` INT NULL,
  `id_aporte` INT NULL,
  INDEX `fk_movimientos_clase_marcador1_idx` (`id_marcador` ASC) VISIBLE,
  INDEX `fk_movimientos_clase_aporte1_idx` (`id_aporte` ASC) VISIBLE,
  INDEX `fk_movimientos_clase_comentario1_idx` (`id_comentario` ASC) VISIBLE,
  INDEX `fk_movimientos_clase_asistencia1_idx` (`id_asistencia` ASC) VISIBLE,
  INDEX `fk_movimientos_clase_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_movimientos_clase`),
  INDEX `fk_movimientos_clase_clase1_idx` (`id_clase` ASC) VISIBLE,
  CONSTRAINT `fk_movimientos_clase_marcador1`
    FOREIGN KEY (`id_marcador`)
    REFERENCES `mydbDotCLASS`.`marcador` (`idmarcador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_clase_aporte1`
    FOREIGN KEY (`id_aporte`)
    REFERENCES `mydbDotCLASS`.`aporte` (`idaporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_clase_comentario1`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `mydbDotCLASS`.`comentario` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_clase_asistencia1`
    FOREIGN KEY (`id_asistencia`)
    REFERENCES `mydbDotCLASS`.`asistencia` (`idasistencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_clase_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydbDotCLASS`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_clase_clase1`
    FOREIGN KEY (`id_clase`)
    REFERENCES `mydbDotCLASS`.`clase` (`idclase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`examen` (
  `idexamen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`idexamen`),
  INDEX `fk_examen_curso1_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_examen_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydbDotCLASS`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`pregunta` (
  `idpregunta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `id_examenl` INT NOT NULL,
  PRIMARY KEY (`idpregunta`),
  INDEX `fk_pregunta_examen1_idx` (`id_examenl` ASC) VISIBLE,
  CONSTRAINT `fk_pregunta_examen1`
    FOREIGN KEY (`id_examenl`)
    REFERENCES `mydbDotCLASS`.`examen` (`idexamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`alternativa` (
  `idalternativa` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `id_pregunta` INT NOT NULL,
  PRIMARY KEY (`idalternativa`),
  INDEX `fk_alternativa_pregunta1_idx` (`id_pregunta` ASC) VISIBLE,
  CONSTRAINT `fk_alternativa_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `mydbDotCLASS`.`pregunta` (`idpregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`respuesta` (
  `idrespuesta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `id_pregunta` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`),
  INDEX `fk_respuesta_pregunta1_idx` (`id_pregunta` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `mydbDotCLASS`.`pregunta` (`idpregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbDotCLASS`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbDotCLASS`.`blog` (
  `idblog` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `like` INT NOT NULL,
  `id_suscripcion` INT NOT NULL,
  PRIMARY KEY (`idblog`),
  INDEX `fk_blog_suscripcion1_idx` (`id_suscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_blog_suscripcion1`
    FOREIGN KEY (`id_suscripcion`)
    REFERENCES `mydbDotCLASS`.`suscripcion` (`idsuscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
